language: java

jdk:
  - openjdk7
  - oraclejdk7
 
branches:
  only:
    - develop
    - master

addons:
  # set short to avoid https://github.com/travis-ci/travis-ci/issues/5227
  hostname: test-openjdk7

before_script: cd java

script: ant clean-integrationtest 
# ant clean-webdriver
# ^^ smoke tests depend on localhost serving example/cardorder for webdriver tests -- host servlet at svea & switch to headless driver to enable these in future /kgm
